# Generated by Django 3.2.8 on 2021-10-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_oder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
    ]
